spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: andrei.cioropar.stmp@gmail.com #gmail password Testpass12#
    password: joppwqlqpwslkxdi
    protocol: smtp
    test-connection: false
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  jwt:
    secret: CHANGE_ME
