server:
  servlet:
    context-path: /api
  error:
    include-stacktrace: never

spring:
  application:
    name: hospital-app
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 300000
  jpa:
    properties:
      hibernate:
        default_schema: public
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  main:
    allow-circular-references: true
  banner:
    location: banner.txt
  mail:
    host: CHANGE_ME
    port: CHANGE_ME
    username: CHANGE_ME
    password: CHANGE_ME
    protocol: smtp
    test-connection: false
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  liquibase:
    change-log: classpath:db/db.changelog-master.xml

# Swagger Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Application Information
module-name: "hospital-server"
api-version: "1.0"

# Security Configuration
security:
  apis:
    public-endpoints:
      - method: POST
        uris:
          - /auth/login
          - /user
          - /user/registration/**
          - /patient/registration/**
      - method: GET
        uris:
          - /medic/**
          - /swagger-ui/**
          - /v3/api-docs/**
          - /error/**
          - /management/**
  cors:
    config:
      allowed-origins: ["*"]  # Consider restricting origins in production
      allowed-methods:
        - POST
        - GET
        - PUT
        - DELETE
      allowed-headers:
        - Content-Type
        - Authorization
        - Accept
      exposed-headers:
        - Location

# Password Reset Configuration
app:
  jwt:
    secret: CHANGE_ME
  password-reset:
    expire-in: 5
  mail:
    REGISTER_ACCOUNT:
      template-name: register-account
      additional-details:
        registerLink: http://localhost:4200/register/step-two/{token}



