INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, PHONE, EMAIL, GENDER, ROLE) VALUES (1, 'Andrei', 'Test', '123123', 'andrei@ad.com', 'MALE', 'Admin');

INSERT INTO MEDIC (MEDIC_ID, FIRST_NAME, LAST_NAME, MOBILE_PHONE, EMAIL) VALUES (1, 'Olivia', 'Oli', '0753455584', 'olvas@asd.com');
INSERT INTO MEDIC (MEDIC_ID, FIRST_NAME, LAST_NAME, MOBILE_PHONE, EMAIL) VALUES (2, 'Ordos', 'Adi', '0753455584', 'ordos@asd.com');

INSERT INTO PATIENT (PATIENT_ID, AGE, CNP, DIAGNOSIS, FIRST_NAME, INDICATIONS, LAST_NAME, MOBILE_PHONE, OBSERVATIONS) VALUES (1, 30, 12312349, 'Cardio', 'Tom', 'TODO', 'John', 1234123, 'Obs');

INSERT INTO APPOINTMENT (APPOINTMENT_ID, PATIENT_ID, APPOINTMENT_DETAILS, START_DATE) VALUES (1, 1, 'Programat pentru coro', TO_DATE('2022-10-03 15:00:00', 'YYYY-MM-DD HH:MI:SS'));

INSERT INTO PATIENT_MEDIC (PATIENT_ID, MEDIC_ID) VALUES (1, 1);